### ISSUE TITLE
Beta Image for Application

### ISSUE THREAD

**Issue by tracicakes** [HospitalRun/design#2]
Hey @jglovier! Can you help me out with a image for the application with the logo? Im pretty sure you will agree that you dislike what this is doing...

https://docs.google.com/forms/u/0/d/1SlTWWoGEc99qYOIwNN_-1TRCrvpeA0uu2cWWpjWE-vA/edit

P.S. questions are VERY rough so don't look at those!!

**Comment by jglovier** [comment]
Ugh...

![image](https://cloud.githubusercontent.com/assets/1319791/15710466/28a51d1e-27d8-11e6-954c-8931fd04314f.png)

**Comment by jglovier** [comment]
Added here: https://github.com/HospitalRun/design/blob/master/marketing/forms/gform-header-img-beta.jpg
