### ISSUE TITLE
Contributor Thank You PostCards

### ISSUE THREAD

**Issue by tracicakes** [HospitalRun/design#4]
I would like a branded Post Card that says...

Options:
A... "Thank you for giving of your time to help make this software great. We couldn't do this alone.  ~From your friends at HospitalRun." 

B... "Thank you for your brain. We couldn't have gotten this far without you. ❤️ HospitalRun"

C... "We know time is important to you. Thanks for giving some to us on this open source project. We couldn't have gotten this far without your help. From all of us @ HospitalRun, THANK YOU!"

@jglovier @tangollama -Opinions or weigh ins here? 

@tangollama Do we have some budget to have these printed??

**Comment by jglovier** [comment]
Curious why a post card, and how we plan to get physical addresses to send it out? Why not just an email?

As for copy options, here's a hybrid suggestion of my own:

> Thank you for contributing your time and expertise to help build HospitalRun. You are helping to improve the state of medical care in areas of the world that need it most. From all of us at HospitalRun, THANK YOU!

**Comment by tracicakes** [comment]
Copy suggestions: 👍 

> Curious why a post card, and how we plan to get physical addresses to send it out? Why not just an email?

We are sending them a t-shirt already. I am gathering physical addresses to send them a gift. I wanted a branded note send inside. That's where my thought was with this.

**Comment by dkaushik95** [comment]
Can I make it on photoshop so that you can print it out ? 
Also Can you give me the dimensions needed in order to make it ?

**Comment by jglovier** [comment]
> I wanted a branded note send inside. That's where my thought was with this.

Ahhhh great idea! 👍 👍

**Comment by tracicakes** [comment]
@dkaushik95 Yes photoshop 👍 And a pdf of it would be great. 😄

**Comment by jglovier** [comment]
@dkaushik95 thanks for jumping in. :heart:

When you have artwork ready for review, feel free to open a pull request to add the files to the `marketing/shirts/insert` directory.

**Comment by dkaushik95** [comment]
@jglovier @tracicakes  Cool! Ill get right to it 😄

**Comment by jglovier** [comment]
@dkaushik95 any update here? Seems like you may not have had a chance to get to this, so I'm going to put the `help-wanted` label on it.

**Comment by dkaushik95** [comment]
@jglovier I am so sorry but I couldn't find time, I have made a pull request, though. Let me know if you want any changes and I'll be happy to do it.

**Comment by jglovier** [comment]
@dkaushik95 no problem!

>I have made a pull request, though. Let me know if you want any changes and I'll be happy to do it.

Where did you make the pull request to? I'm not seeing any new PRs in this repo.

**Comment by dkaushik95** [comment]
Sorry, I didn't know how to, I created a pull request on the forked directory. I've created a pull request now.

**Comment by DerekTBrown** [comment]
@tangollama think this should be closed.
