### ISSUE TITLE
New contributor looking for previous research materials

### ISSUE THREAD

**Issue by skveerkamp** [HospitalRun/design#6]
Hi there! I'm trying to learn more about HospitalRun and its users before I jump in. 
I tried to hunt down some personas or user research and found this: 
https://github.com/HospitalRun/hospitalrun-frontend/wiki/Personas

Is there any other existing research or materials that could help get me up to speed?

**Comment by jglovier** [comment]
Hi @skveerkamp! Thanks for your interest in contributing.

@mnorbeck is going to be adding some more docs to the https://github.com/hospitalRun/planning repo soon that will have a lot more UX context (jobs to be done formatted requirements). Mel, can you please cc both myself and @skveerkamp on the PR when you open it?

Also, @skveerkamp feel free to ping me in our Slack team (there is a #design channel that would be appropriate) and we can chat more about the state of design on the project right now, or any other UX specific questions you have. TL;DR we have a lot of work to do in regards to making the state of design as easy to hop in and contribute as the primary codebase is. Anything you are interested to tackle would be super appreciated!
